services:
    emhar_api_infrastructure.serializer.bad_request_exception_hanlder:
        class: Emhar\ApiInfrastructureBundle\Serializer\BadRequestHttpExceptionHandler
        tags:
            - { name: jms_serializer.subscribing_handler }
    emhar_api_infrastructure.serializer.date_handler:
        class: Emhar\ApiInfrastructureBundle\Serializer\DateHandler
        arguments: ["@translator"]
        tags:
            - { name: jms_serializer.subscribing_handler }
    emhar_api_infrastructure.nelmio.cache_warmer:
        class: Emhar\ApiInfrastructureBundle\Nelmio\Cache\NelmioDocCacheWarmer
        arguments: ["@kernel", "%emhar_api_infrastructure.warm_nelmio_doc%"]
        tags:
            - { name: kernel.cache_warmer }
    emhar_api_infrastructure.nelmio.cache_warmer_with_jms_job:
        class: Emhar\ApiInfrastructureBundle\Nelmio\Cache\NelmioDocCacheWarmerWithJmsJob
        arguments: ["@doctrine", "%emhar_api_infrastructure.warm_nelmio_doc_with_jms_job%"]
        tags:
            - { name: kernel.cache_warmer }